<?php

declare(strict_types=1);

namespace App\Service\OAuth\Contract;

use League\OAuth2\Client\Token\AccessTokenInterface;

/**
 * Abstraction of the Google OAuth provider.
 *
 * This interface decouples the application from the external
 * League OAuth2 Google provider and allows unit testing without
 * relying on the third-party implementation.
 */
interface GoogleOAuthProviderInterface
{
    /**
     * Generates the Google authorization URL.
     */
    public function getAuthorizationUrl(): string;

    /**
     * Returns the OAuth state generated by the provider.
     */
    public function getState(): string;

    /**
     * Exchanges an authorization code for an access token.
     *
     * @param string $code
     *     Authorization code received from Google.
     *
     * @return AccessTokenInterface
     *     OAuth access token.
     */
    public function getAccessToken(string $code): AccessTokenInterface;

    /**
     * Returns the raw Google resource owner data.
     *
     * The returned array corresponds to Google's OpenID Connect
     * user information endpoint and is intentionally left
     * unnormalized. The normalization is performed by
     * GoogleOAuthService.
     *
     * @param AccessTokenInterface $accessToken
     *     OAuth access token.
     *
     * @return array<string,mixed>
     *     Raw user profile returned by Google.
     */
    public function getResourceOwnerData(
        AccessTokenInterface $accessToken
    ): array;
}
